# -*- coding: utf-8 -*-
"""YOSEI-DIF — quiz reconstruits sur les fiches officielles de préformation."""
import json
from pathlib import Path
C = Path(__file__).parent
K = lambda q, o, c: {"q": q, "opts": o, "correct": c}

# ── UF1 : enseignement et animation (fiches UF1a, UF1b, UF1c) ────────────
uf1 = [
 K("Selon la fiche UF1a, l'enseignement est fondé sur l'acquisition de connaissances à transmettre :",
   ["Par l'exemple et la répétition","Avec méthode, sous la forme d'objectifs à atteindre","Par la démonstration technique","Selon le niveau de chacun"],1),
 K("Combien de conditions la fiche UF1a énumère-t-elle pour enseigner ?",["Deux","Trois","Quatre","Six"],2),
 K("Le thème de la séance indique le sujet :",["De manière précise et technique","De manière générique","Sous forme d'objectif mesurable","Sous forme de consigne à l'élève"],1),
 K("L'objectif principal de la séance :",["Reprend le thème mot pour mot","Indique précisément l'élément technique étudié","Décrit l'exercice à réaliser","Fixe le minutage"],1),
 K("Les objectifs poursuivis définissent :",["Le matériel nécessaire","Des paliers d'apprentissage","Le niveau des élèves","La durée de chaque exercice"],1),
 K("Un objectif poursuivi doit être univoque, c'est-à-dire :",["Court et facile à retenir","Formulé en japonais","Impossible à interpréter autrement que ce qui est demandé","Identique pour tous les élèves"],2),
 K("La construction d'un objectif poursuivi se fait en deux temps :",["Le quoi puis le pourquoi","Ce que l'on veut faire, puis comment on veut le faire","Le niveau puis la durée","La technique puis la correction"],1),
 K("« L'objectif poursuivi décrit… »",["Le déroulement de l'exercice","Le produit final de l'action","Le matériel utilisé","La consigne de sécurité"],1),
 K("Cette manière de raisonner découle de :",["La méthode globale","La pédagogie différenciée","La pédagogie par objectifs (PPO)","La pédagogie active"],2),
 K("Le plan de séance type comporte :",["Une seule partie : le tableau","Deux parties : la présentation et le tableau","Trois parties dont une évaluation","Autant de parties que de séquences"],1),
 K("La présentation de la séance se place :",["Dans la première ligne du tableau","En bas de page","En haut de page, à l'extérieur du tableau","Sur une feuille séparée"],2),
 K("Quelles sont les quatre colonnes du plan de séance officiel ?",
   ["Échauffement / Corps / Opposition / Retour au calme",
    "Objectifs poursuivis / Description des exercices / Organisation matérielle et consignes / Minutage",
    "Objectif / Exercice / Sécurité / Évaluation",
    "Temps / Contenu / Consigne / Critère"],1),
 K("La colonne « organisation matérielle et consignes » contient notamment :",
   ["Le nom des élèves","Le matériel, les critères de réalisation, l'intensité et les temps de récupération",
    "Le thème et l'objectif","Les résultats obtenus"],1),
 K("Le champ « élèves concernés » doit préciser :",["Le nombre exact","Le public et son niveau de pratique","Les prénoms","Les grades individuels"],1),
 K("Le plan de séance est décrit dans la fiche UF1b comme :",["Un document administratif","Un tableau de bord","Une fiche d'évaluation","Un support de communication"],1),
 K("Parmi les fonctions du plan de séance figure :",["Justifier le montant de la cotisation","Situer la séance dans la progression","Remplacer le règlement intérieur","Attester de la présence des élèves"],1),
 K("« Prévoir l'utilisation des prérequis », c'est :",["Vérifier les licences","Faire émerger la connaissance des élèves","Contrôler le matériel","Rappeler les règles de sécurité"],1),
 K("Le plan de séance est aussi appelé, dans la fiche :",["Le carnet de bord","Le tableau de commande","La feuille de route","Le cahier des charges"],1),
 K("Connaître sa discipline suppose, selon la fiche UF1a :",["Un palmarès en compétition","Du vécu et un esprit d'analyse","Un grade élevé","Une formation universitaire"],1),
 K("Les objectifs de l'enseignant se classent en deux catégories :",
   ["Techniques et tactiques","Individuels et collectifs",
    "Liés à la progression technique, et liés au calendrier sportif ou au loisir","Court terme et long terme"],2),
]

# ── UF2 : environnement associatif et fédéral ───────────────────────────
uf2 = [
 K("Quelle instance organise la formation DIF ?",["Le comité départemental","La ligue régionale","La zone interdépartementale","La FFK nationale"],1),
 K("Quel est le volume global de la formation DIF ?",["37 heures","40 heures","70 heures","110 heures"],2),
 K("Comment se répartissent les 70 heures du DIF ?",
   ["12 h préformation + 40 h école de formation + 18 h participations fédérales",
    "12 h préformation + 15 h école de formation + 10 h participations",
    "26 h à distance + 43 h présentiel + 40 h stage","34 h UF1 + 17 h UF2 + 19 h UF3 uniquement en présentiel"],0),
 K("Depuis combien de temps faut-il détenir le DAF pour entrer en formation DIF ?",["Six mois","Un an","Deux ans","Aucune ancienneté requise"],1),
 K("Le certificat médical exigé à l'entrée en formation DIF doit dater de moins de :",["Un mois","Trois mois","Six mois","Un an"],1),
 K("Quel volume représente l'UF1 dans le DIF ?",["11 heures","17 heures","19 heures","34 heures"],3),
 K("Dans l'UF1 du DIF, le bloc 1B « concevoir et mettre en œuvre des séances » représente :",["6 heures","12 heures","18 heures","24 heures"],2),
 K("Le bloc 1C du DIF porte sur :",["Les exercices","Les séances","Une saison","L'évaluation"],2),
 K("Un diplôme fédéral peut-il être décerné si les heures de participation fédérale ne sont pas faites ?",
   ["Oui, elles sont facultatives","Oui, avec dérogation du club","Non, aucun diplôme ne peut être validé","Oui, si l'école de formation est validée"],2),
 K("L'AFA permet :",["D'enseigner en autonomie","D'assister un enseignant titulaire au minimum du DAF et présent dans la salle","D'ouvrir un club","D'enseigner contre rémunération"],1),
 K("Le DIF est le prérequis obligatoire de :",["Du BPJEPS","Du CQP MAM","Du DEJEPS","Du DAF"],1),
 K("Le CQP autorise l'enseignement rémunéré dans la limite de :",["180 h par an","250 h par an","360 h par an","Sans limite"],2),
 K("L'évaluation de la préformation se déroule en trois phases :",
   ["Écrit, oral, pratique","Test de connaissances, correction collective interactive, QCM d'évaluation",
    "QCM, entretien, mise en situation","Auto-évaluation, correction, rattrapage"],1),
 K("Les supports de préformation doivent être fournis aux stagiaires :",["Le jour du stage","Une semaine avant","Au minimum un mois avant le début des stages","Après le stage"],2),
 K("Une licence STAPS donne droit, en UF1, à une dispense de :",["4 heures","8 heures","14 heures","Aucune"],1),
 K("Les arbitres nationaux et régionaux bénéficient en UF3 d'une dispense de :",["7 heures","8 heures","14 heures","18 heures"],2),
 K("La saison sportive court du :",["1er janvier au 31 décembre","1er juillet au 30 juin","1er septembre au 31 août","1er octobre au 30 septembre"],2),
 K("Pour les licenciés FFK, le certificat médical est exigé :",
   ["Tous les trois ans, avec questionnaire de santé les autres années","Chaque année, sans exception",
    "Uniquement pour les compétiteurs","Uniquement à la première licence"],1),
 K("Pourquoi la FFK déroge-t-elle au régime triennal du certificat médical ?",
   ["Parce qu'elle est une fédération délégataire","Parce que le combat peut prendre fin sur un état d'incapacité à se défendre",
    "Parce qu'elle propose plusieurs disciplines","Parce que le ministère l'a imposé"],1),
 K("L'obligation d'être licencié concerne :",["Les seuls pratiquants","Les pratiquants et les professeurs","Les pratiquants, les professeurs et tous les dirigeants","Les seuls compétiteurs"],2),
 K("Un dirigeant peut-il être dirigeant de deux clubs affiliés à la FFKDA ?",["Oui, sans restriction","Oui, avec accord des deux présidents","Non, l'article 431 du règlement intérieur l'interdit","Oui, s'il n'est pas rémunéré"],2),
 K("L'organe de direction d'un club affilié doit comporter au minimum :",["Deux personnes","Trois personnes : président, secrétaire général, trésorier","Cinq membres élus","Un président et un trésorier"],1),
 K("À partir de quel âge un mineur peut-il accéder aux fonctions de direction d'une association ?",["14 ans","16 ans révolus","17 ans","18 ans"],1),
 K("Un changement de dirigeant doit être signalé au greffe des associations dans un délai de :",["Huit jours","Un mois","Trois mois","Six mois"],2),
 K("L'ordonnateur des dépenses d'une association est :",["Le trésorier","Le président, sauf stipulation contraire des statuts","Le secrétaire général","L'assemblée générale"],1),
 K("La loi de 1901 impose-t-elle un quorum pour l'assemblée générale ?",["Oui, la moitié des membres","Oui, le tiers des membres","Non, tout dépend des statuts","Oui, pour les seules AG extraordinaires"],2),
 K("Une association loi 1901 peut-elle réaliser des bénéfices ?",
   ["Non, c'est interdit","Oui, seul le partage des bénéfices entre membres est interdit",
    "Oui, dans la limite de 10 % du budget","Uniquement si elle est reconnue d'utilité publique"],1),
 K("Dans quels départements la loi de 1901 ne s'applique-t-elle pas ?",
   ["Corse-du-Sud et Haute-Corse","Haut-Rhin, Bas-Rhin et Moselle","Les départements d'outre-mer","Paris, Lyon et Marseille"],1),
 K("La publication au Journal Officiel des associations coûte :",["Gratuite","31 euros","44 euros","70 euros"],2),
 K("Depuis l'ordonnance du 23 juillet 2015, l'affiliation à une fédération agréée :",
   ["Dispense de statuts","Vaut agrément","Ouvre droit à une subvention automatique","Remplace la déclaration en préfecture"],1),
 K("Une déclaration d'accident doit être faite à l'assureur fédéral dans un délai de :",["48 heures","5 jours","8 jours","1 mois"],1),
 K("Une journée portes ouvertes doit être déclarée à la Mutuelle des Sportifs et à la FFK :",["24 h avant","48 h avant","Une semaine avant","Après l'événement"],1),
 K("Les non-licenciés sont couverts en nombre illimité lors des cours d'essai :",
   ["Toute l'année","Du 1er septembre au 31 octobre","Du 1er septembre au 31 décembre","Jamais"],1),
 K("L'assurance responsabilité civile est :",["Facultative","Obligatoire pour les associations et fédérations sportives","Réservée aux compétiteurs","Incluse dans le passeport sportif"],1),
 K("L'assurance individuelle accident est :",["Obligatoire","Facultative, mais avec obligation d'information de l'adhérent","Interdite","Réservée aux dirigeants"],1),
 K("En cas de manquement à l'obligation d'information sur l'assurance individuelle, le dirigeant :",
   ["N'encourt rien","Encourt des poursuites pénales et engage sa responsabilité civile","Reçoit un simple avertissement fédéral","Doit rembourser la licence"],1),
 K("Les arbitres et juges sont-ils couverts par la responsabilité civile fédérale ?",["Non","Oui, dans l'exercice de leurs activités","Uniquement les arbitres nationaux","Seulement s'ils sont licenciés compétiteurs"],1),
 K("Les justificatifs de frais des bénévoles doivent être conservés par l'association pendant :",["Un an","Deux ans","Trois ans après l'expiration de l'année en cours","Dix ans"],2),
 K("Un bénévole qui renonce au remboursement de ses frais :",
   ["Perd tout avantage","Réalise un don pouvant ouvrir droit à une réduction d'impôt","Doit le déclarer comme un salaire","Ne peut plus demander de remboursement ensuite"],1),
 K("Le remboursement forfaitaire des frais de bénévoles est :",
   ["Recommandé pour simplifier","Déconseillé, admis à titre exceptionnel si l'approximation est sérieuse","Interdit","Obligatoire au-delà de 100 euros"],1),
 K("Combien la FFK compte-t-elle de ligues régionales ?",["9","13","16","22"],1),
 K("Quelle instance encaisse la cotisation fédérale ?",["Le club","Le comité départemental","La ligue régionale","La fédération directement"],2),
 K("Le comité directeur d'un comité départemental compte :",["3 à 8 membres","4 à 14 membres","6 à 14 membres","8 à 14 membres"],1),
 K("Les structures déconcentrées perçoivent-elles une cotisation de leurs membres ?",
   ["Oui, en plus de la cotisation fédérale","Non, seule la cotisation fédérale est obligatoire","Oui, mais facultative","Uniquement les ligues"],1),
 K("La surface minimum d'une aire d'évolution en arts martiaux est de :",["16 m²","20 m²","25 m²","36 m²"],2),
 K("Au-delà de six couples de pratiquants, la surface doit être augmentée de :",["2 m² par couple","4 m² par couple","6 m² par couple","Elle reste inchangée"],1),
 K("Depuis la norme AFNOR NF P 90-209, le capitonnage des obstacles se fait sur une hauteur de :",["1 mètre","1,50 mètre","2 mètres","2,50 mètres"],2),
 K("La température d'une salle d'arts martiaux ne doit pas être inférieure à :",["15 °C","16 °C","18 °C","20 °C"],2),
 K("Les taches de sang sur le tatami doivent être :",["Nettoyées en fin de séance","Immédiatement nettoyées et désinfectées","Simplement recouvertes","Signalées au président"],1),
 K("L'article A322-141 du Code du sport relatif aux salles d'arts martiaux :",
   ["Est toujours en vigueur","A été abrogé et remplacé par la norme AFNOR NF P 90-209","N'a jamais existé","Ne concerne que les salles municipales"],1),
]

quiz = json.loads((C / "quiz.json").read_text(encoding="utf-8"))
quiz["q3"] = {"module": "m3", "titre": "Quiz — Enseignement et animation (UF1)", "statut": "pret",
              "questions": uf1 + quiz["q3"]["questions"]}
quiz["q4"] = {"module": "m4", "titre": "Quiz — Environnement associatif et fédéral (UF2)", "statut": "pret",
              "questions": uf2}
(C / "quiz.json").write_text(json.dumps(quiz, ensure_ascii=False, indent=1), encoding="utf-8")
for k, v in quiz.items():
    print(f"  {k} {v['statut']:12} {len(v['questions']):>3} questions  {v['titre']}")
